#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
	To complete this challenge,
	follow the black line without hitting any obstacles
*/     

#include <../vikaton.h>

task main() {
	int thres = 2273;
	clearLCDLine(0);
	repeat(forever) {
		if (SensorValue(leftLineFollower) > thres) {
			turnX(LEFT, 50, 20);
		}
		if (SensorValue(rightLineFollower) > thres) {
			turnX(RIGHT, 50, 20);
		}
		else {
			moveForward(50, 1);
		}
	}
}
