#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
	To complete this challenge,
	program the robot to move as close to the Pallino (can) as possible without
	bumping it using feedback from the sensors. Once the robot is within roughly
	half the distance of a grid square from the cup,
	it must remain stopped for 5 seconds to complete the challenge.
*/

#include "vikaton.h"

task main() {
	clearLCDLine(0);
	displayLCDString(0, 3,"L | C | R: ");
	turnX(RIGHT, 100, _90DEG);
	repeat(forever) {
		displayLCDNumber(1, 1, SensorValue(leftLineFollower));
		displayLCDNumber(1, 6, SensorValue(rightLineFollower));
		displayLCDNumber(1, 11, SensorValue(centerLineFollower));
		moveForward(20, 1);
	}
}
