#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
	To complete this challenge, program the robot to patrol around the large cube using
	timing or the robot’s encoders. The robot must complete 2 full laps around the object without
	bumping it or falling off of the table.
*/
#include <../vikaton.h>

task main {
	clearLCDLine(0);
	for (int i = 0; i < 4; i++) {
		moveForward(100, 3000);
		turnX(RIGHT, 100, _90DEG);
	}
	displayLCDNumber(0, 0, nMotorEncoder[leftMotor]);
}
