#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
  To complete this challenge, program the robot to drive
  straight through the soda cans without bumping into any of them.
*/

#include <../vikaton.h>

task main() {
	displayLCDCenteredString(0, "Started");
	moveForward(MAX_PORT_NUM, 5000);
	displayLCDCenteredString(0, "Finished");
}
