#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Program your robot, using whatever means necessary, to push 3 full soft drink cans out of the ring.
*/

#include <../vikaton.h>

task main {
	clearLCDLine(0);
	moveForward(MAX_PORT_NUM, 3500);
}
