#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
	To complete this challenge, program the robot to move to the end (the black striped area)
	of the Labyrinth. The robot must NOT cross any of the black lines.
*/
#include <../vikaton.h>

task main() {
	displayLCDCenteredString(0, "Started");
	moveForward(100, 3000);
	turnX(LEFT, 100, _90DEG);
	moveForward(100, 3200);
	turnX(RIGHT, 100, _90DEG);
	moveForward(100, 1500);
	turnX(RIGHT, 100, _90DEG);
	moveForward(100, 1500);
	displayLCDCenteredString(0, "Finished");
}
