#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
	To complete this challenge, program the robot to perform a basketball-like drill.
	Your robot should move to the first line, return to the start, move to the second line,
	return to the start, and so on. The next line that your robot needs to pass is always green.
*/
#include <../vikaton.h>

task main()
{
	for (int i = 1000; i<6000; i+=1500) {
		moveForward(100, i);
		moveBackward(100, i);
	}
}
