/*
	To complete this challenge, program the robot to patrol around the large cube using 
	timing or the robot’s encoders. The robot must complete 2 full laps around the object without 
	bumping it or falling off of the table. 
*/

#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	To complete this challenge, program the robot to accelerate from power level 0
	to power level 127. 
*/

#include "vikaton.h"

task main {
	clearLCDLine(0);
	for (int i = 0; i < 4; i++) {
		while (nMotorEncoder[leftMotor] < 3500) {
			moveForward(100, 0);
		}
		clearEncoders();
		turnX(LEFT,_90DEG);
	}
	displayLCDNumber(0, 0, nMotorEncoder[leftMotor]);
}
