/*
  To complete this challenge, program the robot to drive 
  straight through the soda cans without bumping into any of them. 
*/

#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "vikaton.h"

task main() {
	displayLCDCenteredString(0, "Started");
	moveForward(5000);
	displayLCDCenteredString(0, "Finished");
}
