// I realized there were already forward and backward functions, but WHO CARES
#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "vikaton.h"

task main()
{
	for (int i = 1000; i<6000; i+=2000) {
		moveForward(i);
		moveBackward(i);
	}
}

void moveForward(int i) {
	motor[port1] = 100;
	motor[port10] = 100;
	wait1Msec(i);
}

void moveBackward(int i) {
	motor[port1] = -100;
	motor[port10] = -100;
	wait1Msec(i);
}
